// Generated by /from-issue on 2026-06-01 from Jira SW-6.
// Source: https://diegocortes15.atlassian.net/browse/SW-6
// Title: [SW][QA][Inventory] User can add products to cart
// Augmented by: SW-21 (2026-09-18)
// Manual edits are welcome — this file is not regenerated automatically.
// Re-running /from-issue against a contributing issue will refuse to overwrite.

import { test, expect } from '@fixtures/test';
import { products } from '@data/fixtures';
import type { InventoryPage } from '@pages/InventoryPage';

const BACKPACK = 'Sauce Labs Backpack';
const BIKE_LIGHT = 'Sauce Labs Bike Light';
const BOLT_TSHIRT = 'Sauce Labs Bolt T-Shirt';
const backpack = products.find((p) => p.name === BACKPACK)!;

// SW-21 precondition — a cart that ALREADY holds two products, put there through the UI.
//
// Two rather than one, deliberately (SW-21): a count of one cannot distinguish "the cart
// persisted" from "the cart reset to a default of one".
//
// Deliberately NOT `seedCart`, and the reason is narrower than it first looks. That fixture
// writes `cart-contents` from a `context.addInitScript`, which re-runs on every new DOCUMENT —
// not on every navigation. Measured against this app: removing a product through the UI and
// then opening a product detail page and coming back leaves the cart at one item, because
// saucedemo routes those client-side and no document is created. A RELOAD does create one, and
// the cart jumps back to the seeded value.
//
// So AC 5 alone settles it: seed the cart and `page.reload()` re-seeds it, and the test passes
// while asserting nothing about persistence. The other four would have been fine seeded. All
// five use the UI anyway, because splitting the precondition by which of them survives seeding
// would be a trap for whoever edits this next.
//
// The rule, stated generally so it does not have to be rediscovered: seeding is right when the
// seeded state is setup, and wrong when the subject is that state SURVIVING a document load.
async function holdTwoProductsInCart(inventoryPage: InventoryPage): Promise<void> {
  await inventoryPage.goto();
  await inventoryPage.addToCart(BACKPACK);
  await inventoryPage.addToCart(BIKE_LIGHT);
}

test.describe('cart — standard_user', { tag: '@standard' }, () => {
  test.describe('Positive', () => {
    // AC 1
    test(
      'adding a product shows a cart badge count of one',
      { tag: '@smoke' },
      async ({ inventoryPage }) => {
        await inventoryPage.goto();
        await inventoryPage.addToCart(BACKPACK);
        await expect.poll(() => inventoryPage.getCartBadgeCount()).toBe(1);
      },
    );

    // AC 2 + AC 3 (merged): one add-three flow proves both the badge count and
    // that the cart lists the products in the order they were added.
    test('adding three products shows a badge of three and lists them in add order', async ({
      inventoryPage,
      cartPage,
    }) => {
      await inventoryPage.goto();
      await inventoryPage.addToCart(BACKPACK);
      await inventoryPage.addToCart(BIKE_LIGHT);
      await inventoryPage.addToCart(BOLT_TSHIRT);
      await expect.poll(() => inventoryPage.getCartBadgeCount()).toBe(3);

      await inventoryPage.openCart();
      await expect.poll(() => cartPage.getItemNames()).toEqual([BACKPACK, BIKE_LIGHT, BOLT_TSHIRT]);
    });

    // AC 4
    test('a cart row shows the quantity, title, description, price, and a remove button', async ({
      inventoryPage,
      cartPage,
    }) => {
      await inventoryPage.goto();
      await inventoryPage.addToCart(BACKPACK);
      await inventoryPage.openCart();

      await expect.poll(() => cartPage.getItemNames()).toContain(BACKPACK);
      await expect.poll(() => cartPage.getItemQuantity(BACKPACK)).toBe('1');
      await expect.poll(() => cartPage.getItemDescription(BACKPACK)).toBe(backpack.description);
      await expect.poll(() => cartPage.getItemPrice(BACKPACK)).toBe(backpack.price);
      await expect.poll(() => cartPage.hasRemoveButton(BACKPACK)).toBe(true);
    });

    // AC 5
    test('removing a product drops it from the cart and decrements the badge', async ({
      inventoryPage,
      cartPage,
    }) => {
      await inventoryPage.goto();
      await inventoryPage.addToCart(BACKPACK);
      await inventoryPage.addToCart(BIKE_LIGHT);
      await inventoryPage.openCart();
      await expect.poll(() => cartPage.getCartBadgeCount()).toBe(2);

      await cartPage.removeItem(BACKPACK);
      await expect.poll(() => cartPage.getItemNames()).toEqual([BIKE_LIGHT]);
      await expect.poll(() => cartPage.getCartBadgeCount()).toBe(1);
    });

    // AC 6
    test('continue shopping returns to the inventory page', async ({
      inventoryPage,
      cartPage,
      page,
    }) => {
      await inventoryPage.goto();
      await inventoryPage.addToCart(BACKPACK);
      await inventoryPage.openCart();

      await cartPage.continueShopping();
      await expect(page).toHaveURL(/\/inventory\.html$/);
    });

    // SW-21 AC 1
    test('the cart badge still shows two after opening a product detail page and returning', async ({
      inventoryPage,
      productDetailPage,
    }) => {
      await holdTwoProductsInCart(inventoryPage);

      await inventoryPage.openProductDetail(BACKPACK);
      await productDetailPage.clickBackToProducts();
      await expect.poll(() => inventoryPage.getCartBadgeCount()).toBe(2);
    });

    // SW-21 AC 2
    test('opening the cart lists exactly the two products it holds', async ({
      inventoryPage,
      cartPage,
    }) => {
      await holdTwoProductsInCart(inventoryPage);

      await inventoryPage.openCart();
      await expect.poll(() => cartPage.getItemNames()).toEqual([BACKPACK, BIKE_LIGHT]);
    });

    // SW-21 AC 3
    test('the cart badge still shows two after continue shopping', async ({
      inventoryPage,
      cartPage,
    }) => {
      await holdTwoProductsInCart(inventoryPage);

      await inventoryPage.openCart();
      await cartPage.continueShopping();
      // Asserted as "is 2", never as "the badge is present": saucedemo REMOVES the badge
      // element on an empty cart, so an absence check would pass for a cart that had been
      // reset to nothing (SW-21's note to whoever picks it up).
      await expect.poll(() => inventoryPage.getCartBadgeCount()).toBe(2);
    });
  });

  test.describe('Edge', () => {
    // AC 7
    test('removing the last item hides the cart badge', async ({ inventoryPage, cartPage }) => {
      await inventoryPage.goto();
      await inventoryPage.addToCart(BACKPACK);
      await inventoryPage.openCart();

      await cartPage.removeItem(BACKPACK);
      // The cart is empty: saucedemo removes the badge element entirely (count 0).
      await expect.poll(() => cartPage.getCartBadgeCount()).toBe(0);
      await expect.poll(() => cartPage.getItemCount()).toBe(0);
    });

    // AC 8
    test('adding a product toggles its inventory button to Remove', async ({ inventoryPage }) => {
      await inventoryPage.goto();
      await inventoryPage.addToCart(BACKPACK);
      // saucedemo caps quantity at 1 per product — the Add button becomes Remove.
      await expect.poll(() => inventoryPage.getProductButtonLabel(BACKPACK)).toBe('Remove');
    });

    // AC 9
    test('cart contents persist after continue shopping', async ({ inventoryPage, cartPage }) => {
      await inventoryPage.goto();
      await inventoryPage.addToCart(BACKPACK);
      await inventoryPage.openCart();
      await cartPage.continueShopping();

      await inventoryPage.openCart();
      await expect.poll(() => cartPage.getItemNames()).toEqual([BACKPACK]);
      await expect.poll(() => cartPage.getCartBadgeCount()).toBe(1);
    });

    // SW-21 AC 4 — browser Back out of checkout, not the Cancel button. AC 3 names its
    // control ("Continue Shopping"); AC 4 says only "navigates back", and Cancel's exit
    // already has coverage in checkout.spec.ts (SW-8). Edge rather than Positive: a
    // browser-level navigation is outside the path the application's own controls define.
    test('the cart still lists both products after entering checkout and navigating back', async ({
      inventoryPage,
      cartPage,
      page,
    }) => {
      await holdTwoProductsInCart(inventoryPage);

      await inventoryPage.openCart();
      await cartPage.checkout();
      // Confirms checkout was actually entered, so `goBack` has a step to undo — without
      // it a no-op back would leave the test asserting on the page it never left.
      await expect(page).toHaveURL(/\/checkout-step-one\.html$/);

      await page.goBack();
      await expect.poll(() => cartPage.getItemNames()).toEqual([BACKPACK, BIKE_LIGHT]);
    });

    // SW-21 AC 5
    test('the cart still lists both products after the cart page is reloaded', async ({
      inventoryPage,
      cartPage,
      page,
    }) => {
      await holdTwoProductsInCart(inventoryPage);

      await inventoryPage.openCart();
      await expect.poll(() => cartPage.getItemNames()).toEqual([BACKPACK, BIKE_LIGHT]);

      await page.reload();
      await expect.poll(() => cartPage.getItemNames()).toEqual([BACKPACK, BIKE_LIGHT]);
    });
  });
});
