// Generated by /from-issue on 2026-05-26 from Jira SW-2.
// Source: https://diegocortes15.atlassian.net/browse/SW-2
// Title: [SW][QA][Footer] Verify Footer content
// Augmented by: SW-18 (2026-09-14), SW-20 (2026-09-18)
// Manual edits are welcome — this file is not regenerated automatically.
// Re-running /from-issue against a contributing issue will refuse to overwrite.

import { test, expect } from '@fixtures/test';

// SW-20: the footer is user-agnostic — same DOM on every authenticated page, nothing
// in it depends on who is logged in. It used to be verified once as standard_user;
// @all-users routes these assertions to every chromium-<user> project instead, which
// is what a copyright line reading the same for anybody actually means.
test.describe('footer — all users', { tag: '@all-users' }, () => {
  test.describe('Positive', () => {
    // AC 1–3: each social link points to its canonical Sauce Labs URL.
    // Asserts the anchor's href — we don't navigate to the third-party sites.
    const socialLinks = [
      { network: 'x', label: 'X', href: 'https://x.com/saucelabs' },
      { network: 'facebook', label: 'Facebook', href: 'https://www.facebook.com/saucelabs' },
      {
        network: 'linkedin',
        label: 'LinkedIn',
        href: 'https://www.linkedin.com/company/sauce-labs/',
      },
    ] as const;

    for (const { network, label, href } of socialLinks) {
      test(`footer ${label} link points to its Sauce Labs URL`, async ({ inventoryPage }) => {
        await inventoryPage.goto();
        await expect.poll(() => inventoryPage.footer.getSocialLinkHref(network)).toBe(href);
      });
    }

    // SW-18 AC 2 / SW-20 AC 2: the visible labels. The href assertions above would pass
    // through a rename of an anchor's text, which is half of what the X rebrand changed.
    // SW-18 covered the X label alone; SW-20 extends the same check to all three.
    for (const { network, label } of socialLinks) {
      test(`footer ${label} link shows the label ${label}`, async ({ inventoryPage }) => {
        await inventoryPage.goto();
        await expect.poll(() => inventoryPage.footer.getSocialLinkLabel(network)).toBe(label);
      });
    }

    // SW-20 AC 1: the copyright line, with the year read from the page's OWN clock.
    // This replaces SW-2's literal '2026'. The year is not hardcoded for two reasons,
    // and the second is the one that matters: nobody should edit a test every January,
    // and the application computes the year itself — so a dynamic expectation is the
    // one that still catches a defect. If Sauce Labs ever ships a frozen literal, the
    // footer disagrees with the calendar and this goes red, which is the real bug.
    test("footer copyright line matches the browser's current year", async ({ inventoryPage }) => {
      await inventoryPage.goto();
      const year = await inventoryPage.footer.getPageYear();
      await expect
        .poll(() => inventoryPage.footer.getCopyrightText())
        .toBe(`© ${year} Sauce Labs. All Rights Reserved. Terms of Service | Privacy Policy`);
    });
  });
  // Negative + Edge describes omitted — footer content verification is all Positive.
});
