// Generated by /from-issue on 2026-05-26 from Jira SW-2.
// Source: https://diegocortes15.atlassian.net/browse/SW-2
// Title: [SW][QA][Footer] Verify Footer content
// Augmented by: SW-18 (2026-09-14)
// Manual edits are welcome — this file is not regenerated automatically.
// Re-running /from-issue against a contributing issue will refuse to overwrite.

import { test, expect } from '@fixtures/test';

// Footer content is identical for every user, so it is verified once as
// standard_user (@standard) rather than per-user.
test.describe('footer — standard_user', { tag: '@standard' }, () => {
  test.describe('Positive', () => {
    // AC 1–3: each social link points to its canonical Sauce Labs URL.
    // Asserts the anchor's href — we don't navigate to the third-party sites.
    const socialLinks = [
      { network: 'x', label: 'X', href: 'https://x.com/saucelabs' },
      { network: 'facebook', label: 'Facebook', href: 'https://www.facebook.com/saucelabs' },
      {
        network: 'linkedin',
        label: 'LinkedIn',
        href: 'https://www.linkedin.com/company/sauce-labs/',
      },
    ] as const;

    for (const { network, label, href } of socialLinks) {
      test(`footer ${label} link points to its Sauce Labs URL`, async ({ inventoryPage }) => {
        await inventoryPage.goto();
        expect(await inventoryPage.footer.getSocialLinkHref(network)).toBe(href);
      });
    }

    // AC 4: copyright line renders verbatim.
    test('footer shows the Sauce Labs copyright text', async ({ inventoryPage }) => {
      await inventoryPage.goto();
      expect(await inventoryPage.footer.getCopyrightText()).toBe(
        '© 2026 Sauce Labs. All Rights Reserved. Terms of Service | Privacy Policy',
      );
    });

    // SW-18 AC 2: the X link's visible label. The href assertion above would pass
    // through a rename of the anchor's text, which is half of what the rebrand changed.
    test('footer X link shows the label X', async ({ inventoryPage }) => {
      await inventoryPage.goto();
      expect(await inventoryPage.footer.getSocialLinkLabel('x')).toBe('X');
    });
  });
  // Negative + Edge describes omitted — footer content verification is all Positive.
});
