// Generated by /scaffold-page-object on 2026-05-26.
// Tests using this Page Object are generated by /from-issue (Phase C.2)
// from Jira tickets. Manual edits are welcome — this file is
// not regenerated automatically.

import { test, type Locator, type Page } from '@playwright/test';
import { Footer } from '@components/Footer';
import { Header } from '@components/Header';
import {
  abortRequests,
  readImageStates,
  PRODUCT_IMAGE_URL_GLOB,
  type ImageLoadState,
} from '@utils/network';

export class InventoryPage {
  // Composed components first (ADR-0001 rule #6).
  readonly footer: Footer;
  readonly header: Header;
  // Page-direct locators second.
  private readonly title: Locator;
  private readonly productImages: Locator;
  private readonly productNames: Locator;
  private readonly productDescriptions: Locator;
  private readonly productPrices: Locator;
  private readonly addToCartButtons: Locator;
  // Sort control — saucedemo's ordering control is a native <select> (no separate
  // filter widget); activeSortOption mirrors the currently-selected option's label.
  private readonly sortDropdown: Locator;
  private readonly activeSortOption: Locator;

  constructor(public readonly page: Page) {
    this.footer = new Footer(page);
    this.header = new Header(page);
    this.title = page.locator('[data-test="title"]');
    // Each product image carries its OWN data-test (`inventory-item-<product>-img`,
    // verified live), so the collection has no shared value to select on.
    this.productImages = page.locator('img.inventory_item_img');
    this.productNames = page.locator('[data-test="inventory-item-name"]');
    this.productDescriptions = page.locator('[data-test="inventory-item-desc"]');
    this.productPrices = page.locator('[data-test="inventory-item-price"]');
    this.addToCartButtons = page.getByRole('button', { name: /^Add to cart$/i });
    this.sortDropdown = page.locator('[data-test="product-sort-container"]');
    this.activeSortOption = page.locator('[data-test="active-option"]');
  }

  // Composed / intent-level action — body wrapped in exactly one test.step.
  async goto(): Promise<void> {
    await test.step('Navigate to the inventory page', async () => {
      await this.page.goto('/inventory.html');
      // `page.goto` resolves on the document, not on the client-rendered product list, and ten
      // tests in this feature read a list on the very next line. On chromium the render always
      // won that race. WebKit did not: one full run in five failed "every product price is
      // formatted with a leading dollar sign" against a short list, and the same test passed
      // every time in isolation — the signature of a race, not a bug in the assertion.
      //
      // Waiting here fixes all ten at once and makes readiness a property of the page rather
      // than a discipline each test has to remember. Not a fixed sleep: this is Playwright's
      // own auto-waiting, so it costs nothing once the list is up.
      await this.productNames.first().waitFor({ state: 'visible' });
    });
  }

  // Query — page title ("Products" on the inventory page). Mirrors
  // CartPage.getTitle(); used by SW-11 to confirm "All Items" lands here.
  async getTitle(): Promise<string> {
    return (await this.title.textContent())?.trim() ?? '';
  }

  // Query — returns data, never a Locator (ADR-0001 rule #8).
  async getProductImageSources(): Promise<string[]> {
    return this.productImages.evaluateAll((imgs) =>
      imgs.map((img) => img.getAttribute('src') ?? ''),
    );
  }

  async getProductNames(): Promise<string[]> {
    return (await this.productNames.allTextContents()).map((name) => name.trim());
  }

  async getProductDescriptions(): Promise<string[]> {
    return (await this.productDescriptions.allTextContents()).map((desc) => desc.trim());
  }

  async getProductPrices(): Promise<string[]> {
    return (await this.productPrices.allTextContents()).map((price) => price.trim());
  }

  async getAddToCartButtonCount(): Promise<number> {
    return this.addToCartButtons.count();
  }

  async getEnabledAddToCartButtonCount(): Promise<number> {
    return this.addToCartButtons.evaluateAll(
      (buttons) => buttons.filter((button) => !(button as HTMLButtonElement).disabled).length,
    );
  }

  // Exact-match title locator — substring hasText could match two cards when one
  // product name contains another (per playwright-conventions.md "Exact-match for
  // named-element filters").
  private productTitle(productName: string): Locator {
    return this.page.getByText(productName, { exact: true });
  }

  // Computed text color of a single product's title — used to verify the hover state.
  async getProductTitleColor(productName: string): Promise<string> {
    return this.productTitle(productName).evaluate((el) => getComputedStyle(el).color);
  }

  // Composed action — wrapped in exactly one test.step (playwright-conventions).
  async hoverProductTitle(productName: string): Promise<void> {
    await test.step(`Hover the "${productName}" product title`, async () => {
      await this.productTitle(productName).hover();
    });
  }

  // Composed action — open a product's detail page by clicking its title.
  // The title text sits inside the card's anchor, so the click bubbles to it and
  // navigates to /inventory-item.html?id=<n> — verified live rather than assumed,
  // since the anchor's href is "#" and the routing is client-side (SW-12).
  // Per ADR-0001 rule #3 this returns void: the test navigates explicitly and
  // then uses the injected productDetailPage fixture.
  async openProductDetail(productName: string): Promise<void> {
    await test.step(`Open the "${productName}" product detail page`, async () => {
      await this.productTitle(productName).click();
    });
  }

  // Composed action — selects a sort option by its <option> value
  // (az | za | lohi | hilo). Native <select>, so selectOption sets it directly.
  async sortBy(optionValue: string): Promise<void> {
    await test.step(`Sort products by "${optionValue}"`, async () => {
      await this.sortDropdown.selectOption(optionValue);
    });
  }

  // Query — the label of the currently-selected sort option (ADR-0001 rule #8).
  async getActiveSortLabel(): Promise<string> {
    return (await this.activeSortOption.textContent())?.trim() ?? '';
  }

  // --- Cart (SW-6) ---

  // A single product card, scoped by its title. Exact match so a short name
  // can't also match a longer one that contains it (playwright-conventions
  // "Exact-match for named-element filters").
  private productCard(productName: string): Locator {
    return this.page.locator('[data-test="inventory-item"]').filter({
      has: this.page.getByText(productName, { exact: true }),
    });
  }

  // Composed action — add one product to the cart from its card.
  async addToCart(productName: string): Promise<void> {
    await test.step(`Add "${productName}" to the cart`, async () => {
      await this.productCard(productName)
        .getByRole('button', { name: /^Add to cart$/i })
        .click();
    });
  }

  // Composed action — open the cart from the header.
  async openCart(): Promise<void> {
    await this.header.openCart();
  }

  // Composed action — log out from the header burger menu (SW-10). Delegates to
  // the Header's BurgerMenu component (composition rule #10), like openCart().
  async logout(): Promise<void> {
    await this.header.burgerMenu.logout();
  }

  // Query — the label of a product card's cart button ("Add to cart" → "Remove"
  // after it's added; saucedemo caps quantity at 1 per product).
  //
  // The name filter is NOT optional. A card holds three elements with role=button: the
  // image link and the title link are `<a href="#" role="button">`, and only the third is
  // the real `<button>`. An unfiltered `getByRole('button')` matched one of them for
  // months and then resolved to three the day the app added those role attributes,
  // failing two tests in strict mode. Anchored, and covering both labels the button
  // takes, because the label is the thing being read.
  async getProductButtonLabel(productName: string): Promise<string> {
    return (
      (
        await this.productCard(productName)
          .getByRole('button', { name: /^(Add to cart|Remove)$/i })
          .textContent()
      )?.trim() ?? ''
    );
  }

  // Query — cart count from the header badge; 0 when the badge is absent.
  async getCartBadgeCount(): Promise<number> {
    return this.header.getCartItemCount();
  }

  // --- Image-load resilience (SW-19) ---

  // A single product card's image. Reuses the card scope, so the name filter decides
  // which of the six this is.
  private productImage(productName: string): Locator {
    return this.productCard(productName).locator('img.inventory_item_img');
  }

  // Composed action — make every product image fail to load, as a blocked CDN would.
  // Call BEFORE goto(): a route only affects requests issued after it is installed.
  async blockProductImages(): Promise<void> {
    await test.step('Block every product image request', async () => {
      await abortRequests(this.page, PRODUCT_IMAGE_URL_GLOB);
    });
  }

  // Composed action — make ONE product's image fail while the rest keep loading, then
  // reload so the page re-requests them under the new route.
  async blockProductImage(productName: string): Promise<void> {
    // The URL has to come from the rendered card rather than be hardcoded: the asset
    // filename carries a build hash (sauce-backpack-1200x1500-CjRW-Djj.jpg), so a redeploy
    // would silently leave a literal pattern matching nothing — and a test that blocks
    // nothing passes for the wrong reason (the trap SW-19 names). Read outside the step
    // below because the empty-src guard is a conditional, which eslint's
    // playwright/no-conditional-in-test flags anywhere inside a test.step body.
    const source = await this.productImage(productName).getAttribute('src');
    if (!source) throw new Error(`No image src found for product "${productName}"`);

    await test.step(`Block the "${productName}" product image and reload`, async () => {
      await abortRequests(this.page, `**${source}`);
      // The image already loaded on this page view, so the route has nothing to catch
      // until the page asks for it again.
      await this.page.reload();
      await this.productNames.first().waitFor({ state: 'visible' });
    });
  }

  // Queries — return load state as data, never a Locator (ADR-0001 rule #8).
  async getProductImageStates(): Promise<ImageLoadState[]> {
    return readImageStates(this.productImages);
  }

  async getProductImageState(productName: string): Promise<ImageLoadState> {
    const [state] = await readImageStates(this.productImage(productName));
    if (!state) throw new Error(`No product image found for "${productName}"`);
    return state;
  }

  // Query — whether the card for this product shows its name as visible text. Scoped to
  // the card so it answers "this product is still identifiable", not "the string appears
  // somewhere on the page".
  async isProductNameVisible(productName: string): Promise<boolean> {
    return this.productCard(productName).getByText(productName, { exact: true }).isVisible();
  }
}
