// Generated by /scaffold-page-object on 2026-09-06.
// Tests using this Page Object are generated by /from-issue (Phase C.2)
// from Jira tickets. Manual edits are welcome — this file is
// not regenerated automatically.

import { test, type Locator, type Page } from '@playwright/test';
import { Footer } from '@components/Footer';
import { Header } from '@components/Header';
import {
  abortRequests,
  readImageStates,
  PRODUCT_IMAGE_URL_GLOB,
  type ImageLoadState,
} from '@utils/network';

export class ProductDetailPage {
  // Composed components first (ADR-0001 rule #6).
  readonly footer: Footer;
  readonly header: Header;
  // Page-direct locators second. The product fields are data-test attributes (selector
  // order #1) scoped to a detail-only container, for the reason spelled out in the
  // constructor.
  private readonly detail: Locator;
  private readonly productName: Locator;
  private readonly productDescription: Locator;
  private readonly productPrice: Locator;
  private readonly addToCartButton: Locator;
  private readonly backToProductsButton: Locator;
  private readonly productImage: Locator;

  constructor(public readonly page: Page) {
    this.footer = new Footer(page);
    this.header = new Header(page);
    // saucedemo reuses the SAME data-test values for a detail page's product fields and for
    // each card in the inventory grid: `inventory-item-name`, `-desc` and `-price` match once
    // here and SIX times there, and `[data-test$="-img"]` likewise. So these hooks are unique
    // on this page and ambiguous on the page you arrive from, which made every read a race —
    // land early and the locator resolves against the grid, and Playwright raises a
    // strict-mode violation. That throws instead of resolving, so `expect.poll` aborts rather
    // than retrying, and the test fails. It was reproduced 3 times in 8 full-suite runs.
    //
    // Scoping to a container that exists ONLY on the detail page turns that race into a
    // non-event: on the inventory the container matches nothing, so the child locator matches
    // nothing, and Playwright auto-waits — zero matches is a wait, many matches is an error.
    // This is the pattern CartPage already uses with `[data-test="cart-list"]`, which is why
    // the cart never had this bug.
    //
    // The container is a CSS class because the hierarchy offers nothing better: the detail page
    // has no container of its own carrying a data-test (`inventory-container` is on both pages,
    // `inventory-item` matches six on the grid), and no heading role at all. Prefer data-test,
    // but when data-test cannot give a unique selector, take the next level that can — and say
    // which level, and why, at the call site.
    this.detail = page.locator('.inventory_details');
    this.productName = this.detail.locator('[data-test="inventory-item-name"]');
    this.productDescription = this.detail.locator('[data-test="inventory-item-desc"]');
    this.productPrice = this.detail.locator('[data-test="inventory-item-price"]');
    // The image's data-test embeds the product slug (`item-sauce-labs-backpack-img`), so the
    // suffix is the only constant part — still a data-test, and unambiguous once scoped.
    this.productImage = this.detail.locator('[data-test$="-img"]');
    // These two are unique on every page they appear on, so they need no scoping.
    this.addToCartButton = page.locator('[data-test="add-to-cart"]');
    this.backToProductsButton = page.locator('[data-test="back-to-products"]');
  }

  // Composed / intent-level action — body wrapped in exactly one test.step.
  // saucedemo addresses a detail page by numeric id, not by product name
  // (/inventory-item.html?id=4 is the Sauce Labs Backpack). Tests that start
  // from the inventory page should use InventoryPage.openProductDetail(name)
  // instead, so the id stays out of the spec.
  async goto(productId: number): Promise<void> {
    await test.step(`Navigate to the product detail page for id ${productId}`, async () => {
      await this.page.goto(`/inventory-item.html?id=${productId}`);
    });
  }

  // Queries — return data, never a Locator (ADR-0001 rule #8).
  async getProductName(): Promise<string> {
    return (await this.productName.textContent())?.trim() ?? '';
  }

  async getProductDescription(): Promise<string> {
    return (await this.productDescription.textContent())?.trim() ?? '';
  }

  async getProductPrice(): Promise<string> {
    return (await this.productPrice.textContent())?.trim() ?? '';
  }

  // Query — cart count from the header badge; 0 when the badge is absent.
  // Mirrors InventoryPage.getCartBadgeCount().
  async getCartBadgeCount(): Promise<number> {
    return this.header.getCartItemCount();
  }

  // Primitives — single-element actions, NOT wrapped in test.step (Playwright
  // already records the underlying click).
  async clickAddToCart(): Promise<void> {
    await this.addToCartButton.click();
  }

  async clickBackToProducts(): Promise<void> {
    await this.backToProductsButton.click();
  }

  // --- Image-load resilience (SW-19) ---

  // Composed action — make the product image fail to load, as a blocked CDN would.
  // Call BEFORE navigating here: a route only affects requests issued after it is
  // installed. The glob covers the inventory page's images too, which is what a test
  // that reaches this page by clicking through the catalog wants.
  async blockProductImages(): Promise<void> {
    await test.step('Block every product image request', async () => {
      await abortRequests(this.page, PRODUCT_IMAGE_URL_GLOB);
    });
  }

  // Query — the detail image's load state as data, never a Locator (rule #8).
  async getProductImageState(): Promise<ImageLoadState> {
    const [state] = await readImageStates(this.productImage);
    if (!state) throw new Error('No product image found on the product detail page');
    return state;
  }
}
