// Generated by /scaffold-page-object on 2026-09-06.
// Tests using this Page Object are generated by /from-issue (Phase C.2)
// from Jira tickets. Manual edits are welcome — this file is
// not regenerated automatically.

import { test, type Locator, type Page } from '@playwright/test';
import { Footer } from '@components/Footer';
import { Header } from '@components/Header';
import {
  abortRequests,
  readImageStates,
  PRODUCT_IMAGE_URL_GLOB,
  type ImageLoadState,
} from '@utils/network';

export class ProductDetailPage {
  // Composed components first (ADR-0001 rule #6).
  readonly footer: Footer;
  readonly header: Header;
  // Page-direct locators second. Every one resolved to a data-test attribute —
  // each was checked against the rendered DOM rather than read off the snapshot
  // (selector order #1, no downgrades).
  private readonly productName: Locator;
  private readonly productDescription: Locator;
  private readonly productPrice: Locator;
  private readonly addToCartButton: Locator;
  private readonly backToProductsButton: Locator;
  private readonly productImage: Locator;

  constructor(public readonly page: Page) {
    this.footer = new Footer(page);
    this.header = new Header(page);
    this.productName = page.locator('[data-test="inventory-item-name"]');
    this.productDescription = page.locator('[data-test="inventory-item-desc"]');
    this.productPrice = page.locator('[data-test="inventory-item-price"]');
    this.addToCartButton = page.locator('[data-test="add-to-cart"]');
    this.backToProductsButton = page.locator('[data-test="back-to-products"]');
    // The detail image's data-test embeds the product slug (`item-sauce-labs-backpack-img`),
    // so there is no constant value to select on — the suffix is the shared part. Still a
    // data-test attribute (selector order #1), and it stays unique: the only other images
    // here are the menu icons and the back arrow, whose data-test values don't end in -img.
    this.productImage = page.locator('[data-test$="-img"]');
  }

  // Composed / intent-level action — body wrapped in exactly one test.step.
  // saucedemo addresses a detail page by numeric id, not by product name
  // (/inventory-item.html?id=4 is the Sauce Labs Backpack). Tests that start
  // from the inventory page should use InventoryPage.openProductDetail(name)
  // instead, so the id stays out of the spec.
  async goto(productId: number): Promise<void> {
    await test.step(`Navigate to the product detail page for id ${productId}`, async () => {
      await this.page.goto(`/inventory-item.html?id=${productId}`);
    });
  }

  // Queries — return data, never a Locator (ADR-0001 rule #8).
  async getProductName(): Promise<string> {
    return (await this.productName.textContent())?.trim() ?? '';
  }

  async getProductDescription(): Promise<string> {
    return (await this.productDescription.textContent())?.trim() ?? '';
  }

  async getProductPrice(): Promise<string> {
    return (await this.productPrice.textContent())?.trim() ?? '';
  }

  // Query — cart count from the header badge; 0 when the badge is absent.
  // Mirrors InventoryPage.getCartBadgeCount().
  async getCartBadgeCount(): Promise<number> {
    return this.header.getCartItemCount();
  }

  // Primitives — single-element actions, NOT wrapped in test.step (Playwright
  // already records the underlying click).
  async clickAddToCart(): Promise<void> {
    await this.addToCartButton.click();
  }

  async clickBackToProducts(): Promise<void> {
    await this.backToProductsButton.click();
  }

  // --- Image-load resilience (SW-19) ---

  // Composed action — make the product image fail to load, as a blocked CDN would.
  // Call BEFORE navigating here: a route only affects requests issued after it is
  // installed. The glob covers the inventory page's images too, which is what a test
  // that reaches this page by clicking through the catalog wants.
  async blockProductImages(): Promise<void> {
    await test.step('Block every product image request', async () => {
      await abortRequests(this.page, PRODUCT_IMAGE_URL_GLOB);
    });
  }

  // Query — the detail image's load state as data, never a Locator (rule #8).
  async getProductImageState(): Promise<ImageLoadState> {
    const [state] = await readImageStates(this.productImage);
    if (!state) throw new Error('No product image found on the product detail page');
    return state;
  }
}
