// Generated by /from-issue on 2026-06-02 from Jira SW-7.
// Source: https://diegocortes15.atlassian.net/browse/SW-7
// Title: [SW][QA][Checkout] User fill mandatory information
// Augmented by: SW-8 (2026-06-02), SW-9 (2026-06-02)
// Manual edits are welcome — this file is not regenerated automatically.
// Re-running /from-issue against a contributing issue will refuse to overwrite.

import { test, expect, type SeedCart } from '@fixtures/test';
import { products } from '@data/fixtures';
import type { InventoryPage } from '@pages/InventoryPage';
import type { CartPage } from '@pages/CartPage';
import type { CheckoutInfoPage } from '@pages/checkout/CheckoutInfoPage';

const BACKPACK = 'Sauce Labs Backpack';
const VALID_INFO = { firstName: 'John', lastName: 'Doe', postalCode: '12345' } as const;

// SW-9 — the three products added (in this order) for the overview scenarios.
const CART_PRODUCT_NAMES = [
  'Sauce Labs Backpack',
  'Sauce Labs Bike Light',
  'Sauce Labs Bolt T-Shirt',
] as const;
// Expected per-product details pulled from the shared catalog — single source of
// truth, so the overview's name/description/price assertions can't drift from data/.
const CART_PRODUCTS = CART_PRODUCT_NAMES.map((name) => {
  const product = products.find((p) => p.name === name);
  if (!product) throw new Error(`Product not found in the catalog: ${name}`);
  return product;
});

// Shared SW-9 precondition: land on Checkout: Overview with the three products in the cart.
//
// The cart is SEEDED. Each test using this asserts something about the overview screen or
// about leaving it — none is about adding to a cart — so the nine UI actions it used to take
// were setup, shared by six tests. The cost was never the seconds: it was that changing the
// "Add to cart" button turned six overview tests red for something they do not test.
async function reachCheckoutOverview(
  seedCart: SeedCart,
  checkoutInfoPage: CheckoutInfoPage,
): Promise<void> {
  await seedCart(CART_PRODUCT_NAMES);
  await checkoutInfoPage.goto();
  await checkoutInfoPage.fillInformation(
    VALID_INFO.firstName,
    VALID_INFO.lastName,
    VALID_INFO.postalCode,
  );
  await checkoutInfoPage.clickContinue();
}

// The same destination, reached the way a customer reaches it. Used by the @smoke test only.
//
// Smoke is build verification: its job is to fail when the purchase journey is broken. A
// smoke test that seeded its cart would pass with the "Add to cart" button dead, which is
// exactly the regression the tier exists to catch. Seeding is for setup; here the journey IS
// the subject.
async function reachCheckoutOverviewByClicking(
  inventoryPage: InventoryPage,
  cartPage: CartPage,
  checkoutInfoPage: CheckoutInfoPage,
): Promise<void> {
  await inventoryPage.goto();
  for (const name of CART_PRODUCT_NAMES) {
    await inventoryPage.addToCart(name);
  }
  await inventoryPage.openCart();
  await cartPage.checkout();
  await checkoutInfoPage.fillInformation(
    VALID_INFO.firstName,
    VALID_INFO.lastName,
    VALID_INFO.postalCode,
  );
  await checkoutInfoPage.clickContinue();
}

test.describe('checkout — standard_user', { tag: '@standard' }, () => {
  test.describe('Positive', () => {
    // AC 1 + AC 2: the cart's Checkout button is shown and lands on the
    // Checkout: Your Information page.
    test('checkout button on the cart page navigates to Checkout: Your Information', async ({
      inventoryPage,
      cartPage,
      checkoutInfoPage,
      page,
    }) => {
      await inventoryPage.goto();
      await inventoryPage.addToCart(BACKPACK);
      await inventoryPage.openCart();

      await expect(cartPage.checkoutButton).toBeVisible();
      await cartPage.checkout();

      await expect(page).toHaveURL(/\/checkout-step-one\.html$/);
      await expect.poll(() => checkoutInfoPage.getTitle()).toBe('Checkout: Your Information');
    });

    // AC 8: the three mandatory inputs render their placeholder text.
    test('mandatory fields show their placeholder text', async ({ checkoutInfoPage }) => {
      await checkoutInfoPage.goto();
      await expect
        .poll(() => checkoutInfoPage.getPlaceholders())
        .toEqual({
          firstName: 'First Name',
          lastName: 'Last Name',
          postalCode: 'Zip/Postal Code',
        });
    });

    // AC 9: a complete, valid information form routes to Checkout: Overview.
    test(
      'valid information routes to Checkout: Overview',
      { tag: '@smoke' },
      async ({ inventoryPage, cartPage, checkoutInfoPage, checkoutOverviewPage, page }) => {
        await inventoryPage.goto();
        await inventoryPage.addToCart(BACKPACK);
        await inventoryPage.openCart();
        await cartPage.checkout();

        await checkoutInfoPage.fillInformation(
          VALID_INFO.firstName,
          VALID_INFO.lastName,
          VALID_INFO.postalCode,
        );
        await checkoutInfoPage.clickContinue();

        await expect(page).toHaveURL(/\/checkout-step-two\.html$/);
        await expect.poll(() => checkoutOverviewPage.getTitle()).toBe('Checkout: Overview');
      },
    );

    // AC 1 + AC 2 (SW-8): the exit controls render on the information page.
    test('Cancel button and cart icon are visible on the Checkout: Your Information page', async ({
      checkoutInfoPage,
    }) => {
      await checkoutInfoPage.goto();
      await expect(checkoutInfoPage.cancelButton).toBeVisible();
      await expect(checkoutInfoPage.cartIcon).toBeVisible();
    });

    // AC 3 + AC 4 (SW-8): both exit controls return the user to the Cart page.
    // The differing step is the CheckoutInfoPage method named in the table, applied
    // unconditionally — no branch in the test body (eslint no-conditional-in-test).
    const exitControls = [
      { name: 'Cancel button', via: 'cancel' },
      { name: 'cart icon', via: 'openCart' },
    ] as const;
    for (const { name, via } of exitControls) {
      test(`${name} returns to the Cart page from Checkout: Your Information`, async ({
        checkoutInfoPage,
        cartPage,
        page,
      }) => {
        await checkoutInfoPage.goto();
        await expect(page).toHaveURL(/\/checkout-step-one\.html$/);

        await checkoutInfoPage[via]();

        await expect(page).toHaveURL(/\/cart\.html$/);
        await expect.poll(() => cartPage.getTitle()).toBe('Your Cart');
      });
    }

    // AC 1 + AC 7 (SW-9): the overview lists each cart product — in the order it
    // was added — with its name, quantity, description, and price.
    test('overview lists the three products in cart order with name, quantity, description, and price', async ({
      seedCart,
      checkoutInfoPage,
      checkoutOverviewPage,
    }) => {
      await reachCheckoutOverview(seedCart, checkoutInfoPage);

      await expect
        .poll(() => checkoutOverviewPage.getProductNames())
        .toEqual(CART_PRODUCTS.map((p) => p.name));
      await expect.poll(() => checkoutOverviewPage.getProductQuantities()).toEqual(['1', '1', '1']);
      await expect
        .poll(() => checkoutOverviewPage.getProductDescriptions())
        .toEqual(CART_PRODUCTS.map((p) => p.description));
      await expect
        .poll(() => checkoutOverviewPage.getProductPrices())
        .toEqual(CART_PRODUCTS.map((p) => p.price));
    });

    // AC 2 + AC 3 (SW-9): the payment and shipping information sections show their values.
    test('overview shows the payment and shipping information', async ({
      seedCart,
      checkoutInfoPage,
      checkoutOverviewPage,
    }) => {
      await reachCheckoutOverview(seedCart, checkoutInfoPage);

      await expect.poll(() => checkoutOverviewPage.getPaymentInfo()).toBe('SauceCard #31337');
      await expect
        .poll(() => checkoutOverviewPage.getShippingInfo())
        .toBe('Free Pony Express Delivery!');
    });

    // AC 4 + AC 5 + AC 6 (SW-9): the price summary shows the item total, the 8% tax,
    // and the order total for the three-item cart ($29.99 + $9.99 + $15.99 = $55.97;
    // tax = round($55.97 * 0.08) = $4.48; total = $60.45).
    test('overview shows the item total, tax, and order total', async ({
      seedCart,
      checkoutInfoPage,
      checkoutOverviewPage,
    }) => {
      await reachCheckoutOverview(seedCart, checkoutInfoPage);

      await expect.poll(() => checkoutOverviewPage.getItemTotalText()).toBe('Item total: $55.97');
      await expect.poll(() => checkoutOverviewPage.getTaxText()).toBe('Tax: $4.48');
      await expect.poll(() => checkoutOverviewPage.getTotalText()).toBe('Total: $60.45');
    });

    // AC 8 (SW-9): the header cart icon is displayed and returns to the Cart page.
    test('cart icon on the overview navigates to the Cart page', async ({
      seedCart,
      cartPage,
      checkoutInfoPage,
      checkoutOverviewPage,
      page,
    }) => {
      await reachCheckoutOverview(seedCart, checkoutInfoPage);

      await expect(checkoutOverviewPage.cartIcon).toBeVisible();
      await checkoutOverviewPage.openCart();

      await expect(page).toHaveURL(/\/cart\.html$/);
      await expect.poll(() => cartPage.getTitle()).toBe('Your Cart');
    });

    // AC 10–13 (SW-9): Finish is visible and completes the order — landing on
    // Checkout: Complete! with both confirmation messages and a Back Home button.
    test(
      'finishing the order shows the confirmation page with a Back Home button',
      { tag: '@smoke' },
      async ({
        inventoryPage,
        cartPage,
        checkoutInfoPage,
        checkoutOverviewPage,
        checkoutCompletePage,
        page,
      }) => {
        await reachCheckoutOverviewByClicking(inventoryPage, cartPage, checkoutInfoPage);

        await expect(checkoutOverviewPage.finishButton).toBeVisible();
        await checkoutOverviewPage.finish();

        await expect(page).toHaveURL(/\/checkout-complete\.html$/);
        await expect.poll(() => checkoutCompletePage.getTitle()).toBe('Checkout: Complete!');
        await expect
          .poll(() => checkoutCompletePage.getCompleteHeader())
          .toBe('Thank you for your order!');
        // Live copy differs slightly from SW-9's paraphrase ("dispatched, and will
        // arrive just as fast…") — the app is the source of truth for exact strings.
        await expect
          .poll(() => checkoutCompletePage.getCompleteText())
          .toBe(
            'Your order has been dispatched, and will arrive just as fast as the pony can get there!',
          );
        await expect(checkoutCompletePage.backHomeButton).toBeVisible();
      },
    );
  });

  test.describe('Negative', () => {
    // AC 3–6: saucedemo validates required fields sequentially (First → Last →
    // Zip), reports the first missing one, and flags all three inputs at once.
    const validationCases = [
      {
        desc: 'all fields empty',
        firstName: '',
        lastName: '',
        postalCode: '',
        error: 'Error: First Name is required',
      },
      {
        desc: 'only first name',
        firstName: 'John',
        lastName: '',
        postalCode: '',
        error: 'Error: Last Name is required',
      },
      {
        desc: 'only last name',
        firstName: '',
        lastName: 'Doe',
        postalCode: '',
        error: 'Error: First Name is required',
      },
      {
        desc: 'only postal code',
        firstName: '',
        lastName: '',
        postalCode: '12345',
        error: 'Error: First Name is required',
      },
    ];

    for (const { desc, firstName, lastName, postalCode, error } of validationCases) {
      test(`continue with ${desc} shows "${error}" and flags all fields`, async ({
        checkoutInfoPage,
      }) => {
        await checkoutInfoPage.goto();
        await checkoutInfoPage.fillInformation(firstName, lastName, postalCode);
        await checkoutInfoPage.clickContinue();

        await expect(checkoutInfoPage.errorBanner).toHaveText(error);
        await expect.poll(() => checkoutInfoPage.getErroredFieldCount()).toBe(3);
        await expect.poll(() => checkoutInfoPage.getErrorIconCount()).toBe(3);
      });
    }
  });

  test.describe('Edge', () => {
    // AC 7: dismissing the error clears the banner and the per-field error
    // styling, while preserving whatever the user already typed.
    test('dismissing the error clears the banner and field styling but keeps entered values', async ({
      checkoutInfoPage,
    }) => {
      await checkoutInfoPage.goto();
      await checkoutInfoPage.fillInformation('John', '', '');
      await checkoutInfoPage.clickContinue();
      await expect(checkoutInfoPage.errorBanner).toBeVisible();
      await expect.poll(() => checkoutInfoPage.getErroredFieldCount()).toBe(3);

      await checkoutInfoPage.dismissError();
      await expect(checkoutInfoPage.errorBanner).toBeHidden();
      await expect.poll(() => checkoutInfoPage.getErroredFieldCount()).toBe(0);
      await expect.poll(() => checkoutInfoPage.getErrorIconCount()).toBe(0);
      expect((await checkoutInfoPage.getEnteredValues()).firstName).toBe('John');
    });

    // AC 5 (SW-8): the form is not persisted — leaving via Cancel and returning
    // shows all three fields empty.
    test('entered information does not persist after leaving via Cancel and returning', async ({
      inventoryPage,
      cartPage,
      checkoutInfoPage,
      page,
    }) => {
      await inventoryPage.goto();
      await inventoryPage.addToCart(BACKPACK);
      await inventoryPage.openCart();
      await cartPage.checkout();

      await checkoutInfoPage.fillInformation('Jane', 'Doe', '12345');
      await checkoutInfoPage.cancel();
      await expect(page).toHaveURL(/\/cart\.html$/);

      await cartPage.checkout();
      await expect(page).toHaveURL(/\/checkout-step-one\.html$/);
      await expect
        .poll(() => checkoutInfoPage.getEnteredValues())
        .toEqual({
          firstName: '',
          lastName: '',
          postalCode: '',
        });
    });

    // AC 6 (SW-8): Cancel bypasses validation — an empty form returns to the Cart
    // page (no "field is required" error blocks the exit).
    test('cancelling an empty form returns to the Cart page without a validation error', async ({
      inventoryPage,
      cartPage,
      checkoutInfoPage,
      page,
    }) => {
      await inventoryPage.goto();
      await inventoryPage.addToCart(BACKPACK);
      await inventoryPage.openCart();
      await cartPage.checkout();
      await expect(page).toHaveURL(/\/checkout-step-one\.html$/);

      await checkoutInfoPage.cancel();

      await expect(page).toHaveURL(/\/cart\.html$/);
      await expect.poll(() => cartPage.getTitle()).toBe('Your Cart');
    });

    // AC 9 (SW-9): Cancel on the overview returns to the inventory page and leaves
    // the three products in the cart (the order isn't discarded).
    test('cancel on the overview returns to the inventory page and keeps the cart', async ({
      seedCart,
      inventoryPage,
      checkoutInfoPage,
      checkoutOverviewPage,
      page,
    }) => {
      await reachCheckoutOverview(seedCart, checkoutInfoPage);

      await checkoutOverviewPage.cancel();

      await expect(page).toHaveURL(/\/inventory\.html$/);
      await expect.poll(() => inventoryPage.getCartBadgeCount()).toBe(3);
    });

    // AC 14 (SW-9): after finishing, Back Home returns to the inventory page and
    // resets the cart — the badge count disappears.
    test('back home after finishing clears the cart and returns to the inventory page', async ({
      seedCart,
      inventoryPage,
      checkoutInfoPage,
      checkoutOverviewPage,
      checkoutCompletePage,
      page,
    }) => {
      await reachCheckoutOverview(seedCart, checkoutInfoPage);
      await checkoutOverviewPage.finish();
      await expect(page).toHaveURL(/\/checkout-complete\.html$/);

      await checkoutCompletePage.backHome();

      await expect(page).toHaveURL(/\/inventory\.html$/);
      await expect.poll(() => inventoryPage.getCartBadgeCount()).toBe(0);
    });
  });
});
