// Generated by /scaffold-page-object on 2026-05-26.
// Tests using this component are generated by /from-issue (Phase C.2)
// from Jira tickets. Manual edits are welcome — this file is
// not regenerated automatically.

import { type Locator, type Page } from '@playwright/test';

// The saucedemo footer is DOM-identical on every authenticated page
// (data-test="footer"), so it lives as a shared component rather than
// page-direct locators.
export type SocialNetwork = 'x' | 'facebook' | 'linkedin';

export class Footer {
  readonly root: Locator;
  private readonly copyright: Locator;
  private readonly socialLinks: Record<SocialNetwork, Locator>;

  constructor(public readonly page: Page) {
    this.root = page.locator('[data-test="footer"]');
    this.copyright = page.locator('[data-test="footer-copy"]');
    this.socialLinks = {
      x: page.locator('[data-test="social-x"]'),
      facebook: page.locator('[data-test="social-facebook"]'),
      linkedin: page.locator('[data-test="social-linkedin"]'),
    };
  }

  // Queries — return data, never a Locator (ADR-0001 rule #8).
  async getSocialLinkHref(network: SocialNetwork): Promise<string> {
    return (await this.socialLinks[network].getAttribute('href')) ?? '';
  }

  // SW-18: the visible label, which the href alone does not catch — the rebrand
  // changed the anchor's text as well as its target.
  async getSocialLinkLabel(network: SocialNetwork): Promise<string> {
    return (await this.socialLinks[network].textContent())?.trim() ?? '';
  }

  async getCopyrightText(): Promise<string> {
    return (await this.copyright.textContent())?.trim() ?? '';
  }

  // SW-20: the application computes the copyright year from the browser's clock —
  // verified by shifting the clock before any page script ran (2027 and 2030 both
  // rendered). So the expected year has to come from the SAME clock the page used,
  // not from the test process: two clocks in different time zones disagree for a
  // few hours either side of midnight on 31 December, and that is not a defect.
  async getPageYear(): Promise<number> {
    return this.page.evaluate(() => new Date().getFullYear());
  }
}
